name: Java Build

on:
    workflow_call:
        inputs:
            sonar-enabled:
                required: true
                type: string
            dp-check-enabled:
                required: true
                type: string

jobs:
    build:
        runs-on: ${{ vars.RUNNER }}
        steps:
            - name: checkout repository
              uses: actions/checkout@v4