name: Build

on:
  workflow_call:
    inputs:
      enable-sonar:
        required: true
        type: string
      java-version:
        required: true
        type: string
    outputs:
      version:
        value: ${{ jobs.build.outputs.version }}

env: 
  JAVA_VERSION: ${{ inputs.java-version }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      version: ${{ steps.extract-version.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract version
        id: extract-version
        run: echo "version=1.0.8" >> $GITHUB_OUTPUT
